# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ryan Tanaka
email: ryanyt@hawaii.edu
description: > # this means to ignore newlines until "baseurl:"
  Ryan Tanaka's homepage :)
baseurl: "" # the subpath of your site, e.g. /blog
url: "/jekyll-simple" # the base hostname & protocol for your site
twitter_username:
github_username: ryantanaka
linkedin_username: ryan-tanaka

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics:
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->

collections:
    projects:
        output: true
